@extends('layouts.master')

@section('title', 'Home')

@section('content')

<h1>about</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus efficitur aliquam semper. Donec erat nunc, mollis nec egestas auctor, elementum sit amet dui. Quisque nec aliquam tellus. Donec sagittis ornare lacus vitae consectetur. In laoreet finibus ex, quis porttitor massa aliquet suscipit. Integer consequat sodales ex, ut lobortis felis egestas sed. Sed pellentesque egestas volutpat.</p>
<p>Donec ac ultrices risus. Mauris dapibus lacus ac feugiat fringilla. Quisque vestibulum lacinia cursus. Duis at libero nisl. Nunc nec dolor ac elit eleifend sagittis. Donec cursus, quam non elementum fermentum, enim elit venenatis justo, et mollis ligula mauris nec metus. Nullam massa ligula, rhoncus sed molestie non, elementum eget magna. Suspendisse tempus tortor vitae vestibulum rutrum. Maecenas ultrices quis neque in tincidunt. Aenean fermentum congue elit, et iaculis sem. Nam iaculis purus et finibus accumsan. Nullam bibendum ipsum varius, eleifend dui eu, cursus erat. Praesent vehicula lobortis mauris in euismod. Nulla fringilla ultricies neque ut commodo.</p>
          <h1>news</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus efficitur aliquam semper. Donec erat nunc, mollis nec egestas auctor, elementum sit amet dui. Quisque nec aliquam tellus. Donec sagittis ornare lacus vitae consectetur. In laoreet finibus ex, quis porttitor massa aliquet suscipit. Integer consequat sodales ex, ut lobortis felis egestas sed. Sed pellentesque egestas volutpat.</p>
<p>Donec ac ultrices risus. Mauris dapibus lacus ac feugiat fringilla. Quisque vestibulum lacinia cursus. Duis at libero nisl. Nunc nec dolor ac elit eleifend sagittis. Donec cursus, quam non elementum fermentum, enim elit venenatis justo, et mollis ligula mauris nec metus. Nullam massa ligula, rhoncus sed molestie non, elementum eget magna. Suspendisse tempus tortor vitae vestibulum rutrum. Maecenas ultrices quis neque in tincidunt. Aenean fermentum congue elit, et iaculis sem. Nam iaculis purus et finibus accumsan. Nullam bibendum ipsum varius, eleifend dui eu, cursus erat. Praesent vehicula lobortis mauris in euismod. Nulla fringilla ultricies neque ut commodo.</p>
          <h2>something else</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus efficitur aliquam semper. Donec erat nunc, mollis nec egestas auctor, elementum sit amet dui. Quisque nec aliquam tellus. Donec sagittis ornare lacus vitae consectetur. In laoreet finibus ex, quis porttitor massa aliquet suscipit. Integer consequat sodales ex, ut lobortis felis egestas sed. Sed pellentesque egestas volutpat.</p>
<p>Donec ac ultrices risus. Mauris dapibus lacus ac feugiat fringilla. Quisque vestibulum lacinia cursus. Duis at libero nisl. Nunc nec dolor ac elit eleifend sagittis. Donec cursus, quam non elementum fermentum, enim elit venenatis justo, et mollis ligula mauris nec metus. Nullam massa ligula, rhoncus sed molestie non, elementum eget magna. Suspendisse tempus tortor vitae vestibulum rutrum. Maecenas ultrices quis neque in tincidunt. Aenean fermentum congue elit, et iaculis sem. Nam iaculis purus et finibus accumsan. Nullam bibendum ipsum varius, eleifend dui eu, cursus erat. Praesent vehicula lobortis mauris in euismod. Nulla fringilla ultricies neque ut commodo.</p>
<p class="mb-0">Donec ac ultrices risus. Mauris dapibus lacus ac feugiat fringilla. Quisque vestibulum lacinia cursus. Duis at libero nisl. Nunc nec dolor ac elit eleifend sagittis. Donec cursus, quam non elementum fermentum, enim elit venenatis justo, et mollis ligula mauris nec metus. Nullam massa ligula, rhoncus sed molestie non, elementum eget magna. Suspendisse tempus tortor vitae vestibulum rutrum. Maecenas ultrices quis neque in tincidunt. Aenean fermentum congue elit, et iaculis sem. Nam iaculis purus et finibus accumsan. Nullam bibendum ipsum varius, eleifend dui eu, cursus erat. Praesent vehicula lobortis mauris in euismod. Nulla fringilla ultricies neque ut commodo.</p>
@endsection